### ISSUE TITLE
Slow redirection

### ISSUE THREAD

**Issue by wdebusschere** [DeuxHuitHuit/flang_redirection#8] opened 2014-12-27 11:08 UTC
Dear,
We use the latest symphony version, with latest multi-language extensions, works great, but the flang_redirection is very very slow.
http://www.pladutse3.be/
Did we do something wrong?

Wannes

![image](https://cloud.githubusercontent.com/assets/4136426/5561143/25590308-8dc1-11e4-9eda-310611c5dbc4.png)

**Comment by nitriques** [comment] 2015-01-07 21:09
Seems like a web server issue... I have the exact same configuration on many many websites and it works ok all the time.

Maybe a session issue ? I get a longer delay if I delete the php session cookie. Only deleting the flang cookie does not change the response time.

Also, looking at your image, it's not the redirection that is slow: it's the page itself (since the first path is /nl/ already)

Closing as I can't reproduce it.

**Closed by nitriques** 2015-01-07 21:09 UTC

**Comment by wdebusschere** [comment] 2015-01-08 09:05
Yes, was a server issue (external db server, no caching) and didn't add the trailing slash.

**Comment by nitriques** [comment] 2015-01-08 16:32
Great!
